import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import { FirestoreUser, FirestoreCertificate } from './firebase';

export interface VillageHubItem {
  name: string;
  count: number;
  pct: string;
  totalXP: number;
}

export interface CurriculumFolderItem {
  id: string;
  name: string;
  parentId: string | null;
  createdAt: string;
}

export interface CurriculumFileItem {
  id: string;
  name: string;
  subject: string;
  category: string;
  materialType?: string;
  size: string;
  uploadedAt: string;
  folderId?: string;
  externalUrl?: string;
}

export interface ExportDataPayload {
  adminUser: { name: string; mobile: string; role: string };
  usersList: FirestoreUser[];
  villageHubStats: VillageHubItem[];
  certificates: FirestoreCertificate[];
  curriculumFolders: CurriculumFolderItem[];
  curriculumFiles: CurriculumFileItem[];
  totalStudyMinsAll: number;
  totalPointsAll: number;
  dateFilterLabel?: string;
}

// Helper to trigger browser file download
export function triggerFileDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// ==========================================
// EXCEL (.XLSX) EXPORT IMPLEMENTATION
// ==========================================

/**
 * Export Master Multi-Sheet Excel Workbook (.xlsx)
 */
export function exportMasterAnalyticsExcel(payload: ExportDataPayload) {
  const timestamp = new Date().toISOString().split('T')[0];
  const wb = XLSX.utils.book_new();

  // Sheet 1: Executive Overview KPIs
  const summaryRows = [
    { Metric: 'Report Name', Value: 'GyaanBot Primary Education Platform Analytics' },
    { Metric: 'Generated Date', Value: new Date().toLocaleString() },
    { Metric: 'Generated By', Value: `${payload.adminUser.name} (${payload.adminUser.mobile})` },
    { Metric: 'Filtered Period / Date Range', Value: payload.dateFilterLabel || 'Full Analytics (All Time)' },
    { Metric: 'Total Active Students', Value: payload.usersList.filter((u) => u.role === 'student').length },
    { Metric: 'Total Teachers', Value: payload.usersList.filter((u) => u.role === 'teacher').length },
    { Metric: 'Total Administrators', Value: payload.usersList.filter((u) => u.role === 'admin').length },
    { Metric: 'Total Study Hours Logged', Value: Number((payload.totalStudyMinsAll / 60).toFixed(1)) },
    { Metric: 'Total Accumulated Student XP', Value: payload.totalPointsAll },
    { Metric: 'Total Village Hubs Tracked', Value: payload.villageHubStats.length },
    { Metric: 'Total Certificates Issued', Value: payload.certificates.length },
    { Metric: 'Curriculum Resources Library Files', Value: payload.curriculumFiles.length },
  ];
  const wsSummary = XLSX.utils.json_to_sheet(summaryRows);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Executive Summary');

  // Sheet 2: Student & User Directory
  const userRows = payload.usersList.map((u, idx) => ({
    'S.No': idx + 1,
    'User ID / UID': (u as any).uid || u.mobile || 'N/A',
    'Full Name': u.name || 'Anonymous',
    'Mobile Number': u.mobile || '',
    'Role': (u.role || 'student').toUpperCase(),
    'Village Hub / School': u.village || u.school || 'Unspecified',
    'Grade / Class': (u as any).grade || u.standard || 'N/A',
    'Streak (Days)': u.streakDays || 0,
    'XP Points': u.totalPoints || 0,
    'Study Minutes': u.studyMins || 0,
    'Joined Date': (u as any).createdAt ? new Date((u as any).createdAt).toLocaleDateString() : (u.signupDate || 'N/A'),
  }));
  const wsUsers = XLSX.utils.json_to_sheet(userRows.length > 0 ? userRows : [{ Note: 'No user records' }]);
  XLSX.utils.book_append_sheet(wb, wsUsers, 'Student Directory');

  // Sheet 3: Village Hub Activity
  const hubRows = payload.villageHubStats.map((h, idx) => ({
    'S.No': idx + 1,
    'Village Hub / School Name': h.name,
    'Enrolled Students': h.count,
    'Active Engagement Rate': h.pct,
    'Total Accumulated XP': h.totalXP,
  }));
  const wsHubs = XLSX.utils.json_to_sheet(hubRows.length > 0 ? hubRows : [{ Note: 'No hub records' }]);
  XLSX.utils.book_append_sheet(wb, wsHubs, 'Village Hubs');

  // Sheet 4: Certificates Ledger
  const certRows = payload.certificates.map((c, idx) => ({
    'S.No': idx + 1,
    'Certificate ID': c.id,
    'Student Name': c.studentName,
    'Student Mobile': c.studentMobile,
    'Course / Module Title': c.title,
    'Score (%)': c.score || 100,
    'Issue Date': c.date,
    'Verification Status': c.status.toUpperCase(),
  }));
  const wsCerts = XLSX.utils.json_to_sheet(certRows.length > 0 ? certRows : [{ Note: 'No certificate records' }]);
  XLSX.utils.book_append_sheet(wb, wsCerts, 'Certificates Ledger');

  // Sheet 5: Curriculum Inventory
  const currRows = payload.curriculumFiles.map((f, idx) => ({
    'S.No': idx + 1,
    'File Name': f.name,
    'Material Type': f.materialType ? (f.materialType === 'notes' ? 'Notes & Summaries' : f.materialType === 'ebook' ? 'E-Books & Textbooks' : f.materialType === 'pyq' ? 'Previous Year Paper' : f.materialType === 'practice_questions' ? 'Practice Questions' : f.materialType) : 'Notes',
    'Subject': f.subject,
    'Category / Format': f.category,
    'File Size': f.size,
    'Upload Date': f.uploadedAt,
    'External Resource Link': f.externalUrl || 'N/A',
  }));
  const wsCurr = XLSX.utils.json_to_sheet(currRows.length > 0 ? currRows : [{ Note: 'No curriculum files' }]);
  XLSX.utils.book_append_sheet(wb, wsCurr, 'Curriculum Library');

  // Write and download .xlsx
  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  triggerFileDownload(blob, `GyaanBot_Master_Analytics_Report_${timestamp}.xlsx`);
}

/**
 * Single Category Excel Export
 */
export function exportCategoryExcel(categoryName: string, headers: string[], rows: (string | number)[][], filenamePrefix: string) {
  const timestamp = new Date().toISOString().split('T')[0];
  const wb = XLSX.utils.book_new();

  const data = [headers, ...rows];
  const ws = XLSX.utils.aoa_to_sheet(data);
  XLSX.utils.book_append_sheet(wb, ws, categoryName.substring(0, 30));

  const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  triggerFileDownload(blob, `${filenamePrefix}_${timestamp}.xlsx`);
}

// ==========================================
// PDF EXPORT IMPLEMENTATION (jsPDF)
// ==========================================

/**
 * Generate Comprehensive Executive PDF Report
 */
export function exportMasterAnalyticsPDF(payload: ExportDataPayload) {
  const timestamp = new Date().toISOString().split('T')[0];
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  // Document Styling Constants
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = margin;

  // Header Banner
  doc.setFillColor(30, 41, 59); // Slate-800
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setFillColor(224, 122, 95); // Coral Accent
  doc.rect(0, 28, pageWidth, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('GYAANBOT RURAL EDUCATION PLATFORM', margin, 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(203, 213, 225);
  doc.text(`Official Executive Analytics & Performance Report | Generated: ${new Date().toLocaleString()}`, margin, 20);

  y = 38;

  // Admin Meta Info Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 20, 2, 2, 'FD');

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('REPORT METADATA', margin + 4, y + 5);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(`Generated By: ${payload.adminUser.name} (${payload.adminUser.mobile}) | Role: ${payload.adminUser.role.toUpperCase()}`, margin + 4, y + 10);
  doc.text(`Analytics Period: ${payload.dateFilterLabel || 'Full Analytics (All Time)'}`, margin + 4, y + 15);

  y += 26;

  // Executive KPI Summary Section Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('1. Key Performance Metrics Overview', margin, y);
  y += 6;

  // KPI Grid Cards (2x2)
  const cardW = (pageWidth - margin * 2 - 6) / 2;
  const cardH = 16;

  const kpis = [
    { label: 'Total Active Students', val: `${payload.usersList.filter((u) => u.role === 'student').length}` },
    { label: 'Total Village Hubs', val: `${payload.villageHubStats.length}` },
    { label: 'Total Study Hours Logged', val: `${Number((payload.totalStudyMinsAll / 60).toFixed(1))} Hours` },
    { label: 'Certificates Issued', val: `${payload.certificates.length}` },
  ];

  kpis.forEach((kpi, idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const cx = margin + col * (cardW + 6);
    const cy = y + row * (cardH + 4);

    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(203, 213, 225);
    doc.roundedRect(cx, cy, cardW, cardH, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label.toUpperCase(), cx + 4, cy + 5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(kpi.val, cx + 4, cy + 12);
  });

  y += cardH * 2 + 12;

  // Section 2: Rural Village Hub Activity
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('2. Regional Village Hub Performance', margin, y);
  y += 6;

  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, pageWidth - margin * 2, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('VILLAGE HUB / SCHOOL NAME', margin + 3, y + 5);
  doc.text('ENROLLED STUDENTS', margin + 95, y + 5);
  doc.text('ENGAGEMENT %', margin + 140, y + 5);

  y += 7;

  payload.villageHubStats.slice(0, 8).forEach((hub) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = margin;
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(30, 41, 59);
    doc.text(hub.name.substring(0, 45), margin + 3, y + 4);
    doc.text(`${hub.count} students`, margin + 95, y + 4);
    doc.text(hub.pct, margin + 140, y + 4);

    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 6, pageWidth - margin, y + 6);
    y += 7;
  });

  y += 6;

  // Section 3: Issued Certificates Highlights
  if (y > pageHeight - 40) {
    doc.addPage();
    y = margin;
  }

  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('3. Issued Course Certificates Summary', margin, y);
  y += 6;

  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, pageWidth - margin * 2, 7, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('STUDENT NAME', margin + 3, y + 5);
  doc.text('COURSE TITLE', margin + 65, y + 5);
  doc.text('ISSUE DATE', margin + 135, y + 5);
  doc.text('STATUS', margin + 165, y + 5);

  y += 7;

  payload.certificates.slice(0, 8).forEach((cert) => {
    if (y > pageHeight - 20) {
      doc.addPage();
      y = margin;
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(30, 41, 59);
    doc.text(cert.studentName.substring(0, 30), margin + 3, y + 4);
    doc.text(cert.title.substring(0, 35), margin + 65, y + 4);
    doc.text(cert.date, margin + 135, y + 4);
    doc.text(cert.status.toUpperCase(), margin + 165, y + 4);

    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 6, pageWidth - margin, y + 6);
    y += 7;
  });

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let pageNum = 1; pageNum <= totalPages; pageNum++) {
    doc.setPage(pageNum);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(
      `GyaanBot Primary Rural Classrooms Analytics | Page ${pageNum} of ${totalPages} | Confidential Admin Record`,
      margin,
      pageHeight - 6
    );
  }

  // Save PDF
  doc.save(`GyaanBot_Executive_Analytics_Report_${timestamp}.pdf`);
}

/**
 * Export Category-Specific Clean Table PDF Document
 */
export function exportCategoryPDF(title: string, headers: string[], rows: (string | number)[][], filenamePrefix: string) {
  const timestamp = new Date().toISOString().split('T')[0];
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;
  let y = margin;

  // Header Banner
  doc.setFillColor(15, 23, 42); // Dark Navy
  doc.rect(0, 0, pageWidth, 24, 'F');

  doc.setFillColor(129, 178, 154); // Sage Green Accent
  doc.rect(0, 24, pageWidth, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('GYAANBOT DATA REPORT: ' + title.toUpperCase(), margin, 11);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.text(`Generated: ${new Date().toLocaleString()} | Total Records: ${rows.length}`, margin, 18);

  y = 32;

  // Calculate Column Widths
  const availableWidth = pageWidth - margin * 2;
  const colWidth = availableWidth / Math.max(1, headers.length);

  // Draw Table Headers
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, y, availableWidth, 7, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(30, 41, 59);

  headers.forEach((h, i) => {
    doc.text(String(h).toUpperCase(), margin + i * colWidth + 2, y + 5);
  });

  y += 7;

  // Draw Table Rows
  rows.forEach((row) => {
    if (y > pageHeight - 15) {
      doc.addPage();
      y = margin + 10;

      // Repeat Table Header on new page
      doc.setFillColor(241, 245, 249);
      doc.rect(margin, y, availableWidth, 7, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(30, 41, 59);
      headers.forEach((h, i) => {
        doc.text(String(h).toUpperCase(), margin + i * colWidth + 2, y + 5);
      });
      y += 7;
    }

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(51, 65, 85);

    row.forEach((cell, i) => {
      const textVal = String(cell ?? '');
      // Truncate long strings to fit column width
      const maxChars = Math.floor(colWidth / 2.2);
      const truncated = textVal.length > maxChars ? textVal.substring(0, maxChars - 2) + '..' : textVal;
      doc.text(truncated, margin + i * colWidth + 2, y + 4.5);
    });

    doc.setDrawColor(241, 245, 249);
    doc.line(margin, y + 6, pageWidth - margin, y + 6);
    y += 6.5;
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let pageNum = 1; pageNum <= totalPages; pageNum++) {
    doc.setPage(pageNum);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(
      `GyaanBot Platform Report | ${title} | Page ${pageNum} of ${totalPages}`,
      margin,
      pageHeight - 6
    );
  }

  doc.save(`${filenamePrefix}_${timestamp}.pdf`);
}
